trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'corpus'  # Update this with your desired image name
  acrName: 'viper'  # Update this with your ACR name
  acrLoginServer: 'viper.azurecr.io'  # Update this with your ACR login server
  azureSubscription: 'xmen1'  # Update this with your Azure subscription
  appServiceName: 'crudapp1'  # Update this with your Azure App Service name
  resourceGroupName: 'crudapp'  # Update this with your Azure resource group name

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(acrLoginServer)/$(imageName):$(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        tags: |
          $(acrLoginServer)/$(imageName):$(tag)
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)
          az webapp config container set --name $(appServiceName) --resource-group $(resourceGroupName) --docker-custom-image-name $(acrLoginServer)/$(imageName):$(tag) --docker-registry-server-url https://$(acrLoginServer)