trigger:
  branches:
    include:
      - main  

pr:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: docker-registry-variable
  - name: imageName
    value: 'crudapp'  

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build job'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'xmen-connection'  
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo $(Build.BuildId)
          az acr build --registry viper --image $(imageName):$(Build.BuildId) .

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/drop'
        artifact: 'drop'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    steps:
    - download: current
      artifact: 'drop'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'xmen-connection' 
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp config container set --name crudapp1 --resource-group crudapp --docker-custom-image-name viper.azurecr.io/$(imageName):$(Build.BuildId) --docker-registry-server-url https://viper.azurecr.io --docker-registry-server-user $(dockerRegistryUsername) --docker-registry-server-password $(dockerRegistryPassword)
        addSpnToEnvironment: true

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'xmen-connection'  
        appName: 'crudapp1'  
        resourceGroupName: 'crudapp'  
        deployToSlotOrASE: false
        dockerNamespace: 'viper.azurecr.io'
        dockerRepository: $(imageName)
        dockerImageTag: $(Build.BuildId)
        startupCommand: ''

resources:
  containers:
  - container: azurecli
    image: mcr.microsoft.com/azure-cli
    endpoint: xmen-registry
