trigger:
- main  # Replace with your branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: docker-registry-variable
  - name: imageName
    value: 'crudapp'  # Replace with your app's name

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build job'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'xmen-connection'  # Replace with your Azure subscription service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo $(Build.BuildId)
          az acr build --registry viper --image $(imageName):$(Build.BuildId) .

    - publish: $(Pipeline.Workspace)
      artifact: drop
      displayName: 'Publish Artifact: drop'

- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    steps:
    - download: current
      artifact: drop

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'xmen-connection'  # Replace with your Azure subscription service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript:
